# Generated by Django 4.2 on 2025-11-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BraceletDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(default='Mon Bracelet', max_length=100)),
                ('battery_level', models.IntegerField(default=100)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('spo2', models.IntegerField(blank=True, help_text='SpO2 (%)', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='BPM', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='/min', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('REST', 'Repos'), ('LIGHT', 'Léger'), ('MODERATE', 'Modéré'), ('INTENSE', 'Intense')], max_length=20)),
                ('steps', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MODERATE', 'Modéré'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.braceletdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
