# Generated by Django 4.2 on 2025-12-02 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_SPO2', 'SpO2 Faible'), ('HIGH_RESPIRATORY_RATE', 'Fréquence Respiratoire Élevée'), ('POOR_AIR_QUALITY', 'Mauvaise Qualité Air'), ('SMOKE_DETECTED', 'Fumée Détectée'), ('HIGH_POLLEN', 'Pollen Élevé'), ('COMPOSITE_RISK', 'Risque Composite')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Attention'), ('CRITICAL', 'Critique')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('spo2_variation_1h', models.FloatField(blank=True, help_text='Variation SpO2 sur 1h (%)', null=True)),
                ('spo2_avg_1h', models.FloatField(blank=True, help_text='Moyenne SpO2 sur 1h', null=True)),
                ('spo2_min_1h', models.FloatField(blank=True, help_text='Min SpO2 sur 1h', null=True)),
                ('aqi_avg_3h', models.FloatField(blank=True, help_text='AQI moyen sur 3h', null=True)),
                ('aqi_avg_6h', models.FloatField(blank=True, help_text='AQI moyen sur 6h', null=True)),
                ('aqi_avg_24h', models.FloatField(blank=True, help_text='AQI moyen sur 24h', null=True)),
                ('heart_rate_avg_1h', models.FloatField(blank=True, help_text='FC moyenne sur 1h', null=True)),
                ('heart_rate_variability', models.FloatField(blank=True, help_text='Variabilité FC', null=True)),
                ('respiratory_rate_avg_1h', models.FloatField(blank=True, help_text='FR moyenne sur 1h', null=True)),
                ('respiratory_health_score', models.IntegerField(blank=True, help_text='Score santé respiratoire (0-100)', null=True)),
                ('environmental_risk_score', models.IntegerField(blank=True, help_text='Score risque environnemental (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='sensordata',
            name='aqi',
            field=models.IntegerField(blank=True, help_text='Air Quality Index (0-500)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='aqi_avg_3h',
            field=models.FloatField(blank=True, help_text='AQI moyen sur 3h', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='hour_of_day',
            field=models.IntegerField(blank=True, help_text='Heure du jour (0-23)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.IntegerField(blank=True, help_text='Humidité (%)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='pollen_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], help_text='Niveau de pollen', max_length=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='smoke_detected',
            field=models.BooleanField(default=False, help_text='Fumée détectée'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='spo2_variation_1h',
            field=models.FloatField(blank=True, help_text='Variation SpO2 sur 1h', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('REST', 'Repos'), ('WALK', 'Marche'), ('RUN', 'Course')], help_text="Niveau d'activité", max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Fréquence cardiaque (30-220 bpm)', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Fréquence respiratoire (10-40/min)', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='risk_score',
            field=models.IntegerField(blank=True, help_text='Score de risque calculé (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='SpO2 (70-100%)', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Température (°C)', null=True),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['user', '-timestamp'], name='sensors_sen_user_id_6428fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['risk_level', '-timestamp'], name='sensors_sen_risk_le_1607f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['spo2', '-timestamp'], name='sensors_sen_spo2_c1957c_idx'),
        ),
        migrations.AddField(
            model_name='sensoranalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='sensor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensordata'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sensoranalytics',
            index=models.Index(fields=['user', '-timestamp'], name='sensors_sen_user_id_16dc56_idx'),
        ),
    ]
