# Generated by Django 5.1.15 on 2026-01-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_add_ubidots_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='aqi',
            field=models.IntegerField(blank=True, help_text='Air Quality Index externe (0-500)', null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='smoke_detected',
            field=models.BooleanField(default=False, help_text='Fumée détectée - Alerte critique'),
        ),
    ]
