// Importation de toutes les icônes nécessaires de react-icons
import { 
  FaUser, 
  FaEnvelope, 
  FaPhone, 
  FaMapMarkerAlt, 
  FaShieldAlt, 
  FaSignOutAlt, 
  FaPen, 
  FaSpinner, 
  FaLock, 
  FaEye, 
  FaEyeSlash,
  FaChevronLeft,
  FaChevronRight,
  FaExternalLinkAlt,
  FaShoppingCart,
  FaSearch,
  FaSlidersH,
  FaPlus,
  FaSync,
  FaExclamationCircle,
  FaTimes,
  FaCheckCircle,
  FaCar,
  FaBuilding,
  FaUsers,
  FaTrophy,
  FaClock,
  FaCreditCard,
  FaUserCheck,
  FaArrowRight,
  FaStar,
  FaTruck,
  FaHeadphones,
  FaHeart,
  FaCalendar,
  FaTachometerAlt,
  FaGasPump,
  FaCog,
  FaTrash,
  FaEdit,
  FaChartBar
} from 'react-icons/fa';

// Exportation d'un objet qui mappe les noms d'icônes Lucide aux icônes React-icons
export const Icons = {
  User: FaUser,
  Mail: FaEnvelope,
  Phone: FaPhone,
  MapPin: FaMapMarkerAlt,
  ShieldCheck: FaShieldAlt,
  LogOut: FaSignOutAlt,
  PenLine: FaPen,
  Loader2: FaSpinner,
  Lock: FaLock,
  Eye: FaEye,
  EyeOff: FaEyeSlash,
  ChevronLeft: FaChevronLeft,
  ChevronRight: FaChevronRight,
  ExternalLink: FaExternalLinkAlt,
  ShoppingCart: FaShoppingCart,
  Search: FaSearch,
  SlidersHorizontal: FaSlidersH,
  Plus: FaPlus,
  RefreshCw: FaSync,
  AlertCircle: FaExclamationCircle,
  X: FaTimes,
  CheckCircle2: FaCheckCircle,
  Car: FaCar,
  Building2: FaBuilding,
  Users: FaUsers,
  Trophy: FaTrophy,
  Clock: FaClock,
  CreditCard: FaCreditCard,
  UserCheck: FaUserCheck,
  ArrowRight: FaArrowRight,
  Star: FaStar,
  Truck: FaTruck,
  Shield: FaShieldAlt,
  Headphones: FaHeadphones,
  Heart: FaHeart,
  Calendar: FaCalendar,
  Gauge: FaTachometerAlt,
  Fuel: FaGasPump,
  Settings: FaCog,
  Trash2: FaTrash,
  Edit2: FaEdit,
  BarChart3: FaChartBar
};

export default Icons;