# Generated by Django 4.2 on 2025-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('aqi', models.IntegerField(help_text='Air Quality Index')),
                ('aqi_level', models.CharField(choices=[('GOOD', 'Bon'), ('MODERATE', 'Modéré'), ('UNHEALTHY', 'Mauvais')], max_length=20)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='°C')),
                ('humidity', models.IntegerField(help_text='%')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
