# Generated by Django 4.2 on 2025-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airquality',
            name='pm10',
            field=models.FloatField(blank=True, help_text='Particules PM10', null=True),
        ),
        migrations.AddField(
            model_name='airquality',
            name='pollen_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], help_text='Niveau de pollen', max_length=10),
        ),
        migrations.AddField(
            model_name='airquality',
            name='smoke_detected',
            field=models.BooleanField(default=False, help_text="Fumée détectée dans l'environnement"),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='aqi',
            field=models.IntegerField(help_text='Air Quality Index (0-500)'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='aqi_level',
            field=models.CharField(choices=[('GOOD', 'Bon'), ('MODERATE', 'Modéré'), ('UNHEALTHY', 'Mauvais'), ('HAZARDOUS', 'Dangereux')], max_length=20),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm25',
            field=models.FloatField(blank=True, help_text='Particules PM2.5', null=True),
        ),
        migrations.AddIndex(
            model_name='airquality',
            index=models.Index(fields=['city', '-timestamp'], name='environment_city_1c1d77_idx'),
        ),
        migrations.AddIndex(
            model_name='airquality',
            index=models.Index(fields=['aqi_level', '-timestamp'], name='environment_aqi_lev_4082ac_idx'),
        ),
    ]
